# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d4cf93cd89c9e9801cc5e89ac4a3328b80e88d1bb826dd4750a847ac0ed3524beb500a6d96e2025aec5a28c9fecaa5b69232874caa38fc7ca9be624912fbd67

test:
  secret_key_base: a6c2c5f4986a30c6a5a49fec18b887ffecc38fff10e7a6ad5eb8252d4cc4fa2646e00fbd61886abcd11dbf622d473799afed0d1197f6f21e80c01502109a9472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
